### ISSUE TITLE
Xconfig_zcp in release 2.1.0

### ISSUE THREAD

**Issue by N-DucharmeBarth** [James-Thorson-NOAA/VAST#155]
Hi Jim,
I just saw that you released a new feature Xconfig_zcp which should provide greater control on estimating the effect of environmental covariates if I'm interpreting your source code correctly. Do you have any further documentation on the use of this feature?
Best,
Nicholas

**Comment by agruss2** [comment]
Until now, VAST was able to account for the effect of environmental covariates on density (or any other dependent variable) through the gamma_p * X_p term, where gamma_p is the effect of the environmental covariates and X_p is a vector of environmental covariates. 
The new feature Xconfig_zcp was introduced to have a means to estimate a spatially varying coefficient for indices like the PDO or the cold pool extent. 
The new feature Xconfig_zcp is such that the gamma_p * X_p term is now substituted with a (gamma_p + sigma_p * epsilon_p) * X_p term
where epsilon_p is a zero-mean Gaussian Markov random field with unit variance for each covariate p. 
When estimating a spatially varying coefficient, VAST estimates its variance sigma_p^2 as a fixed effect, and estimating sigma_p^2 = 0 results in the reduced, linear effect of the covariate of interest. 
VAST users must specify that for any covariate p that is identical across space whenever intercepts are estimated as fixed effects; they will to do this, for example, when fitting to cold-pool extent. 

I am  just taking a crack at responding to you from the material that Jim kindly shared with me, so that VAST users can have some first information on this useful new feature :)

**Comment by agruss2** [comment]
@James-Thorson-NOAA @N-DucharmeBarth I suggest closing the present issue, now that the paper reporting the above-mentioned developments has been published (https://aslopubs.onlinelibrary.wiley.com/doi/abs/10.1002/lno.11238).

**Comment by James-Thorson** [comment]
Thanks Arnaud for looking through these, and Nicholas for asking originally. Yes, that paper documents the benefits of allowing spatially-varying coefficients.  Xconfig_zcp can also be used to facilitate backwards model selection, by starting all elements at 1 and then changing some to 0 as they drop out.
