### ISSUE TITLE
Adding NOAA color palette

### ISSUE THREAD

**Issue by jordanwatson** [James-Thorson-NOAA/VAST#163]
Hey Jim. Follow-up to my brief email. I put together the updated 508 compliant NOAA colors if you were interested in creating a "NOAA color palette."
https://github.com/jordanwatson/NOAA_Branding/blob/master/NOAA_branding_508.R

**Comment by James-Thorson-NOAA** [comment]
I actually just saw a discussion at the Arctic Report Card editors workshop about #endtherainbow and other protests against RGB color pallettes, including (1) generating unintended patterns due to human sensiivity to green/yellows, (2) colorblindness, and (3) poor matching of continuous transitions with important breakpoints.  I'll try to assemble some thoughts on this thread about what color palette to adopt, but doubt I have time in the short term to address this :0

**Comment by jordanwatson** [comment]
Hi Jim. No worries about this. I believe the new 508 compliant color palettes are meant to deal with some of these issues but mostly I was just thinking about continuity - especially given how many agency folks are using VAST now. Feel free to just ignore this altogether. I've been using the colorblind palettes from color brewer for a long time and those are probably quite adequate and area already built-in to ggplot.

**Comment by James-Thorson-NOAA** [comment]
I'll leave this thread here to solicit feedback on color palettes,
