### ISSUE TITLE
Switch to sp package for projections due to failure in difficult regions like Antarctica

### ISSUE THREAD

**Issue by colemonnahan** [James-Thorson-NOAA/VAST#206]
I have a data set which has points encircling Antarctica. When I try to run VAST I get an index error in TMB and R crashes. It appears this is due to the difficult geography of my data points and that the spatial list and mesh are not being created properly due to projection issues.

Offline discussions with @James-Thorson-NOAA lead us to realize switching to the `sp` package for projections would be more reliable. This issue serves as a general discussion about the pros/cons about upgrading VAST/FishStatsUtils to include this improved projection functionality.

**Comment by James-Thorson-NOAA** [comment]
Thanks Cole!  I will start exploring and documenting ideas on the issue-thread.

I envision leaving `zone` as an argument to all current functions with default `zone=NA` left unchanged.  When this default value is supplied, I envision that it will then use a new argument `projargs` that is passed to package `sp` and where the default value is to detect the same UTM zone as was previously the default for `PBSmapping`.  When an integer is supplied to `zone`, it will similarly coerce that to the equivalent `projargs` string.  This would then eliminate all use of `PBSmapping` and use associate all UTM coordinates with an argument `CRS` resulting from the `projargs` field; thereby maintaining full backwards compatibility while supporting the new argument `projargs`.

**Comment by James-Thorson-NOAA** [comment]
I have made a preliminary commit addressing this issue as outlined above.  It specifically introduces a new function `FishStatsUtils::project_coordinates(.)`, which projects to and from coordinate systems using package `sp` based on the `projargs` input.  `projargs` is now available as input to `make_extrapolation_info(.)`, and is recorded in the output of that function so that its available to subsequent uses of that object.  

The new function allows me to eliminate `PBSmapping` as a dependency, and solves three issues:
1.  ability to easily use other projection methods besides UTM
2.  ability to include data from more than 3 UTM zones before breaking in the default UTM-based projections.
3. automatically detecting and correctly dealing with data that either wrap across the dateline, and/or straddle the equator without any kludges.

The change passes all existing integrated tests and a few ad hoc tests, and I welcome feedback prior to merging to the main branch.
