### ISSUE TITLE
Possible small typo in "VAST_v8_3_0.cpp"

### ISSUE THREAD

**Issue by agruss2** [James-Thorson-NOAA/VAST#207]
Line 1083 - I suspect that
```
eta2_vc = covariation_by_category_nll( OverdispersionConfig(1), n_v, n_c, eta2_vf, eta1_mean_vf, 
  L2_z, Options(14), jnll_comp(5), this );
```
should read:
```
eta2_vc = covariation_by_category_nll( OverdispersionConfig(1), n_v, n_c, eta2_vf, eta2_mean_vf, 
  L2_z, Options(14), jnll_comp(5), this );
```
i.e., 
I suspect that "eta1_mean_vf" should be replaced with: "eta2_mean_vf".

**Comment by James-Thorson-NOAA** [comment]
Thanks for pointing this out. Both eta1_mean_vf and eta2_mean_vf are fixed at zero (they're needed for consistency with other functions), so no bug exactly. But I'll change in 8.4.0 to simplify reading the code.

**Comment by James-Thorson** [comment]
After thinking more, I realized that this issue that you flagged will not affect any results, but the problem *would* cause a crash / model-build error for any model where OverdispersionConfig[1] < OverdispersionConfig[2].  Given that fixing it will avoid some crashes, but otherwise won't affect results, I have gone backwards and fixed it for all versions where it occurred (starting at V7.0.0) in the development branch, which I will obviously merge to main branch sometime soon.  The problem was introduced when I switched to allowing a factor-model for intercepts and used the same function for that and overdispersion.
