### ISSUE TITLE
Observed vs Predicted positive density plots option

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#214]
Is there an option in VAST to display 2D scatterplots of the observed vs. predicted positive density as in Figure 3 of Nikolioudakis et al. 2019

N Nikolioudakis, H J Skaug, A H Olafsdottir, T Jansen, J A Jacobsen, K Enberg
Drivers of the summer-distribution of Northeast Atlantic mackerel (Scomber scombrus) in the Nordic Seas from 2011 to 2017; a Bayesian hierarchical modelling approach.  ICES Journal of Marine Science, Volume 76, Issue 2, March-April 2019, Pages 530–548, https://doi.org/10.1093/icesjms/fsy085

Thank you

**Comment by James-Thorson-NOAA** [comment]
No but Report$R2_i should be the predicted positive catch rate, and TmbData$b_i the observed, and you could make it yourself. If that works and looks right please confirm and close the issue

**Comment by EllenY** [comment]
Seems to look right. Thanks Jim!
![FIGURE 9](https://user-images.githubusercontent.com/7538663/71747023-0c163c80-2e1b-11ea-9c78-b6e6736446c0.jpg)

**Comment by aastarloa** [comment]
Hi, 
I found this question really interesting and I also plotted my observed densities vs the predicted ones. However, due to the large amount of 0s, my R value is far from1. However, the diagnosis plot looks better. Do they mean the same? Should I focus on the diganosis plot rather than in the first scatterplot?
Thanks

![Predicted observed](https://user-images.githubusercontent.com/50455690/82884036-7d2dcc00-9f43-11ea-805d-4f07ff8d652d.png)
![Diag--Encounter_prob](https://user-images.githubusercontent.com/50455690/82884060-84ed7080-9f43-11ea-9ffe-4e1794b6e0f9.png)

**Comment by James-Thorson-NOAA** [comment]
The development branch of VAST/FishStatsUtils now invisibly returns a DHARMa object when running `plot(fit)`, and I encourage you to look there about how to plot observed-vs-predicted values when using probability-integral-transform (PIT) residuals that transfer the delta-model output to quantile-residuals.
