### ISSUE TITLE
Add Covariate data 

### ISSUE THREAD

**Issue by hhamazaki** [James-Thorson-NOAA/VAST#223]
Error in make_covariates(formula = formula, covariate_data = covariate_data,  : 
  Year 1977 not found in `covariate_data` please specify covariate values for all years

I am trying to use survey bottom temp and depth as covariate,  
It seems that covariate data must be annual, regardless surveys did not occur every year.   
Is there an option for this?

**Comment by James-Thorson-NOAA** [comment]
You can set `Year=NA` for any covariate that doesn't change among years (i.e., depth) and it should be smart enough to look at those data when filling in values for any year.  Have you explored this option?

**Comment by hhamazaki** [comment]
It worked after removing NA rows from covariates.

**Comment by James-Thorson** [comment]
Could you close the issue on GitHub?

Thanks for checking and confirming on the thread!

**Comment by hhamazaki** [comment]
Yes, the program worked, but model results will be wrong.   
I can run model with  Year = NA for bottom temp as covariate.   But, this assume that bottom-temp  (or relative spatial temperature gradients?) do not change year by year, which is wrong.   Year = NA 
should work for rocky bottom depth that probably does not change through years.  However, in sandy bottoms (sounds, river bottom), depth will change year by year due to underwater current and discharges.  Thus, navigation charts are always updated.

**Comment by James-Thorson** [comment]
For covariates that change among years you can then specify the column Year
and it will restrict to rows with a given Year value when filling in X_gtp
and X_itp for each Year.

**Comment by aastarloa** [comment]
Hi, 
I'm having the same problem with surface temperature. Before introducing the covariates, I was using "settings$Options["treat_nonencounter_as_zero"] = FALSE" to predict on years with no data, but now it does not work. Could you give more details on what you mean when you say to specify the column Year? Rigth now, I am using "t_i=all$sampling_data[,"Year"]". 
Many thanks

**Comment by James-Thorson-NOAA** [comment]
I'm not following exactly. feel free to email me directly and perhaps generate a minimal example: https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/How-to-create-a-minimal-example

**Comment by aastarloa** [comment]
Hi Jim,
What I was saying is that I have some years on my “covariates data” that don’t have any records (no surveys those years); e.g. 1995. However, on X_xtp, covariates data are included for all years because I was expecting the model to predict for those year with no data. But I get:

Error in make_covariates(formula = formula, covariate_data = covariate_data,  :
  Year 1995 not found in `covariate_data` please specify covariate values for all years

Using Year=NA is not an option, since the covariates I am using change over years. So, I was wondering if there is another way.

By the way, I also wanted to ask another question related to adding covariates. With the old version I was modelling an oceanographic index using the spatially varying effect (ie. Xconfig_zcp=2). Now, with the new interface, the correct form would be to model the index with no splines, right? Like this?
formula = ~ bs(nao, intercept=FALSE)

And if we are modelling temperature with a non-linear effect, e.g. k=3, should we modify Xconfig_zcp too?

Many thanks. Let me know if you want me to move those questions to the github site.
Amaia

De: Jim Thorson <notifications@github.com>
Enviado el: martes, 26 de mayo de 2020 18:33
Para: James-Thorson-NOAA/VAST <VAST@noreply.github.com>
CC: Amaia Astarloa Diaz <aastarloa@azti.es>; Comment <comment@noreply.github.com>
Asunto: Re: [James-Thorson-NOAA/VAST] Add Covariate data (#223)


I'm not following exactly. feel free to email me directly and perhaps generate a minimal example: https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/How-to-create-a-minimal-example<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnwfsc-assess%2Fgeostatistical_delta-GLMM%2Fwiki%2FHow-to-create-a-minimal-example&data=02%7C01%7C%7C9bd1e83ba2ef4563322008d801926aed%7C6219f1193e794e7facdea5750808cd9b%7C0%7C0%7C637261075658629181&sdata=br5P67F5c%2By4%2Flx26sSSEQjvrJH1K4CNvoZeYruJIdc%3D&reserved=0>

**Comment by James-Thorson-NOAA** [comment]
Two quick responses:

1.  There's no other way, you'll need to specify values for all covariates in all modeled years.
2.  Try `formula = ~ nao`
