### ISSUE TITLE
simulator OM = EM

### ISSUE THREAD

**Issue by Charles-Adams-NOAA** [James-Thorson-NOAA/VAST#225]
For our VAST application we want to do a simulation where OM = EM. Toward that end, I've made a few changes (listed below) to the EBS pollock example code on the simulator wiki page. Hyperstability is okay (1.028; SE = 0.02) but bias in average is not (0.92; SE 0.007). Box plot summarizes the relative error (OM$Estimate_metric_tons - EM$Estimate_metric_tons)/ EM$Estimate_metric_tons). If all settings are the same shouldn't OM = EM, i.e., mean bias ± 2SE encompasses 1?

** Change RhoConfig in OM
** RhoConfig = c("Beta1" = 2, "Beta2" = 2, "Epsilon1" = 0, "Epsilon2" = 0))
RhoConfig = c("Beta1" = 0, "Beta2" = 0, "Epsilon1" = 0, "Epsilon2" = 0))

** Set EM settings to same as OM; comment out other mis-specifications
settings_em = settings
** settings_em[['RhoConfig']] = c("Beta1" = 0, "Beta2" = 0, "Epsilon1" = 0, "Epsilon2" = 0)
** settings_em[['ObsModel']] = c(2, 0)
** settings_em[['n_x']] = 50
** settings_em[['bias.correct']] = TRUE

** Change EM newtonsteps to 1
** newtonsteps = 0
newtonsteps = 1

![relative error](https://user-images.githubusercontent.com/25087663/76762608-f5b82580-6767-11ea-93ae-41a860014bcc.png)

**Comment by kellijohnson-NOAA** [comment]
Simulations that I did using VAST as the EM with my own code for the OM showed that VAST is much better at picking up the trend than the absolute abundance.

**Comment by James-Thorson-NOAA** [comment]
I'd be happy to chip in a bit on running code, but first wonder if you could do some exploration on your own.  Have you tried using an EM that follows the conventional "index standardization" settings, i.e., without temporal correlations in intercepts?

**Comment by Charles-Adams-NOAA** [comment]
Yes, I set RhoConfig = c("Beta1" = 0, "Beta2" = 0, "Epsilon1" = 0, "Epsilon2" = 0)) for the OM, and then carried that forward to the EM with settings_em = settings

**Comment by James-Thorson-NOAA** [comment]
I'd like to investigate.  To start, I'd like to replicate what you've done.  What packageVersion do you have for FishStatsUtils and VAST?

**Comment by Charles-Adams-NOAA** [comment]
I'm using the development branch as per the Simulator wiki page:
VAST 3.4.0
FishStatsUtils 2.6.0

Code is identical to that on the Simulator wiki page, with the exception of the few changes noted above to have the same settings for OM & EM. I can also email you a simple example

**Comment by James-Thorson-NOAA** [comment]
Chuck,

I'm just starting to run this. But I think I can guess the problem now that I'm looking closer: you turned off bias-correction.  Could you please try instead:

```R
** Change RhoConfig in OM
** RhoConfig = c("Beta1" = 2, "Beta2" = 2, "Epsilon1" = 0, "Epsilon2" = 0))
RhoConfig = c("Beta1" = 0, "Beta2" = 0, "Epsilon1" = 0, "Epsilon2" = 0))

## Set EM settings to same as OM; comment out other mis-specifications
settings_em = settings
## settings_em[['RhoConfig']] = c("Beta1" = 0, "Beta2" = 0, "Epsilon1" = 0, "Epsilon2" = 0)
## settings_em[['ObsModel']] = c(2, 0)
## settings_em[['n_x']] = 50
settings_em[['bias.correct']] = TRUE

## Change EM newtonsteps to 1
## newtonsteps = 0
newtonsteps = 1
```

...?  This will typically inflate the estimates by 5-10% (based on the sampling densities, domain size, and sampling variance I typically see in bottom trawl surveys) and would likely account for the difference.  I'll try running overnight though.

**Comment by Charles-Adams-NOAA** [comment]
I did that because the simulator code has bias.correct=FALSE for fit_orig. If the objective is OM = EM don't we want settings the same everywhere? Nevertheless will try a run with bias.correct=TRUE throughout

**Comment by James-Thorson-NOAA** [comment]
Chuck,

I finished the run overnight, both using mismatched EM (the original design) and matched EM (your new design) and both were approximately unbiased (they had a ratio of 1.02 and 1.03, which I think is likely due to small sample size of 10 replicates).

The logic of that simulation script is as follows:

1.  I set `settings[["bias.correct"]] = FALSE` to save time during the initial fit -- this fit is intended to get parameter estimates for fixed and random effects, but its estimate of the abundance index is not recorded or used anywhere so using bias-correction for that estimator would be a waste of machine resources.

2.  I then set `settings_em[["bias.correct"]] = TRUE` following guidance from [Thorson 2019](https://www.sciencedirect.com/science/article/abs/pii/S0165783618302820), because these EM replicates are interested in the scale of the abundance index such that bias-correction is important.

I can see why you turned off bias-correction (so that bias-correction is off in the OM and EM).  But it has no affect on the OM anyway (which you could test to convince yourself) and should always be on in the EM for any derived quantity you're interpreting (which your initial experiment showed)
