### ISSUE TITLE
Wiki covariate example for dynamic covariates

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#258]
I would like to test out the wiki covariate example but for a dynamic covariate and missing years. I assume that catch and covariate data are taken from matching locations within each year. Is there additional code for the wiki covariate example to do so? I am using the development versions of VAST and FishStatsUtils downloaded Oct 13 2020. 
Thanks!
https://github.com/James-Thorson-NOAA/VAST/wiki/Specifying-covariates

**Comment by James-Thorson-NOAA** [comment]
For dynamic covariates, you'll need to specify a value for every Lat-Long-Year combination in `covariate_data`.  If you have missing years you can either:

1.  fill in fake values for years between sampled years (which are included in the model to allow for easier switching between models with and without temporal correlations)
2.  renumber the years to range sequentially from 1 to T without any missing integers (and then track that renumbering yourself and use those labels when plotting) -- this will not allow specifying temporal correlations (because the distance between years is not preserved), but is perhaps easier than filling in fake covariate values for missing years.
