### ISSUE TITLE
Including spatio-temporal variation terms in binomial models

### ISSUE THREAD

**Issue by agruss2** [James-Thorson-NOAA/VAST#261]
@James-Thorson-NOAA 
I thought that I would post this issue on GitHub, as it may interest others

I will soon likely start to work on a new NZ project using a combination of encounter/non-encounters, counts and biomasses collected by different monitoring programs, similar to what was done in Grüss & Thorson (2019). 
However, for this new NZ project, there will likely be instances where it will only be possible to combine encounter/non-encounters collected by different monitoring programs, and we will then have to resort to binomial models, similar to what we did to produce distribution maps for ecosystem models for the U.S. Gulf of Mexico. 

The many binomial models that you and I developed with VAST included a spatial variation term, but no spatio-temporal variation term. 
I would prefer the NZ binomial models to include both spatial and spatio-temporal terms. 
My understanding is that we chose not to include any spatio-temporal variation terms in the binomial models for the U.S. Gulf of Mexico because we were only interested in the long-term spatial distribution patterns of the U.S. Gulf of Mexico fishes and not in interannual variability in spatial distribution patterns. 
However, I am not 100% sure, so wanted to write this GitHub issue to: (1) be 100% clear as to why we did not include any spatio-temporal variation terms in the binomial models for U.S. Gulf of Mexico; fishes and (2) understand whether it would be correct to include spatio-temporal variation terms in the binomial models for NZ fishes (and in other case studies). 

Many thanks in advance for your reply!

**Comment by James-Thorson-NOAA** [comment]
Thanks for asking Arnaud!

Yes, I recommend including both spatial and spatio-temporal variation and reducing the model if needed (due to variances going to zero, etc.).  Although see the tree here (https://github.com/James-Thorson-NOAA/VAST/blob/master/manual/VAST_Species_Distribution_Modeling_Workflow.png) for a more structured decision tree, created by @aallyn with input from @afredston.  

I also recommend using a complementary log-log link function (e.g., `ObsModel = c(13,1)`).  However, you might need to build the objects without running, edit the `Map` and `Parameters` by hand, rebuild the object and then run (I'm not sure that `ObsModel = c(13,1)` is implemented to correctly turn off unused parameters when fitted without other data types).  This is because the conventional delta-model will not estimate interpretable "gear performance ratios" (due to its use of a logit-link) in the same way as the complementary log-log link will allow.  I believe we fitted a presence/absence-only-model previous here: https://academic.oup.com/icesjms/article-abstract/76/6/1748/5479986, so perhaps you can find that old code as template. 

Could you please either post more questions or close the issue as appropriate?  We can obviously continue to comment here after closing.

**Comment by agruss2** [comment]
@James-Thorson-NOAA As always, thanks a lot for your prompt reply! This all sounds good to me, and I hope that posting here will also be useful to others. I am going to close this GitHub issue, but may later continue posting some comments/questions here, if need be. 
@aallyn and @afredston : Thanks a lot for the structured decision tree, which is very useful for our VAST community :)
