### ISSUE TITLE
Possible typo in VAST_v13_0_0.cpp

### ISSUE THREAD

**Issue by agruss2** [James-Thorson-NOAA/VAST#285]
In VAST_v13_0_0.cpp of the development branch, line 1969, shouldn't it read:
```TMB
matrix<Type> lowercov_uppercor_beta2 = L_beta2_cf * L_beta2_cf.transpose();
```
instead of:
```TMB
matrix<Type> lowercov_uppercor_beta2 = L_beta1_cf * L_beta1_cf.transpose();
```
? 

Many thanks! (And sorry in case I misunderstood something on the issue of covariance between intercepts).

**Comment by James-Thorson-NOAA** [comment]
Thanks for pointing it out!  Technically this is a bug fix which I'm pushing back to version 7.0.0 of the CPP (where I started providing the option to ADREPORT `lowercov_uppercor_beta2`).  However, I'm not aware of people using this reporting option, so I'm fixing on the development branch rather than a hotfix on the main branch.  I appreciate the close code review and sharp eyes!
