### ISSUE TITLE
Fieldconfig[1,2] = 0 causing TMB to crash with MICE Model

### ISSUE THREAD

**Issue by abesolberg** [James-Thorson-NOAA/VAST#296]
Hi Jim,

I'm trying to run a multispecies model, and I got a message in check_fit that L_omega2_z was approaching 0. In turn, I  changed my settings to turn off Omega 2: 

```
settings = make_settings( n_x=50, purpose = "MICE", Region = './data/2J3K_STRAT_OUTLINE/strat_outline.shp',
                          n_categories = 6) 

# Modify defaults (These are modified in the MICE example)
settings$VamConfig['Rank'] = 1  # Reduce to single axis of ratio-dependent interactions
settings$fine_scale = FALSE  # Make it run faster  
settings$FieldConfig[1,2] = 0 # turn off spatial effects for the 1st second predictor
```

As soon as it then starts making the TMB object, I get the following error:

```
### Making TMB Object
TMB has received an error from Eigen. The following condition was not met: row >= 0 && row < rows() && col >= 0 && col < cols()
Please Check your matrix-vector bounds etc., or run your program through a debugger. 
```

R then crashes and I need to restart. My session info is:

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

FishStatsUtils_2.9.0 
VAST_3.7.0           
TMB_1.7.16           
Matrix_1.2-8

Thanks in advance,
Abe

**Comment by James-Thorson-NOAA** [comment]
Thanks for raising the issue!  However, the MICE model is not currently used for anything besides research;  can you confirm that you only encounter the problem using the MICE model?

**Comment by abesolberg** [comment]
I have not had issues with anything else, but I've mostly been working with the MICE model. 

For reference, I was able to run one model with the same inputs but `"newtonsteps"= 0` with no error, but that model did not converge so I increased the steps to `"newtonsteps"= 1`, which is when I got the  L_omega2_z error, and subsequently changed my fieldconfigs. I tried it as well with the example MICE model, and also changed `settings$FieldConfig[1,2] = 0` and got the same error.

**Comment by James-Thorson-NOAA** [comment]
Feel free to email me directly -- I assume its some silly coding issue with this combination of features, and I can't tell how much time to sink into exploring it without more information about your purpose and goals.  Of course, if you could identify where the crash occurs in the TMB CPP (using a debugger or whatever), that would also make it easier for me to dig in.

The "failure to converge" with `newtonstep=0` I assume just means that `L_omega2_z` is near zero but the gradient is slightly above the default threshold of 0.0001.  Then using `newtonstep=1` gets even closer to zero and below the gradient threshold, but also gets a singular Hessian w.r.t. `L_omega2_z`.  So that behavior is all quite predictable.

I'm closing for now (because I can't commit to maintaining the full feature set for MICE models before its in "operational" use), but feel free to keep responding or email me.

**Comment by abesolberg** [comment]
Hi Jim,

Sounds great! Thank you. I'll keep playing around with it, and will likely reach out over email with more questions.

Thanks again,
Abe
