### ISSUE TITLE
Visualizing covariate effects from a model with factor and continuous, spatially-varying habitat covariates

### ISSUE THREAD

**Issue by aallyn** [James-Thorson-NOAA/VAST#310]
Hi Jim and other VAST folks,

I am curious if anyone has had any luck visualizing covariate effects from a model that has been fit with both a factor and spatially-varying, continuous habitat covariates using either the 'effects' or 'pdp' approaches outlined in the [Wiki example](https://github.com/James-Thorson-NOAA/VAST/wiki/Visualize-covariate-response)? 

I'm running into an error trying to do this for a seasonal model (which has both Year and Season factors). The seasonal models take a while to run. So, as a reproducible example, I did some futzing with the "covariate_example" dataset and was able to get to the same error I'm seeing with the seasonal model using the 'effects' implementation ("Error in mod.matrix %*% scoef : non-conformable arguments"). Reproducible example code is attached, along with some of my thoughts in adjusting the "covariate_example" dataset to demonstrate the issue.

[VASTCovEffectViz_Reprex.txt](https://github.com/James-Thorson-NOAA/VAST/files/6900599/VASTCovEffectViz_Reprex.txt)

Thanks!

**Comment by James-Thorson-NOAA** [comment]
Allan,

Thanks for flagging this.  the marginal-effects plots seem to work in simple instances, but are a new feature and obviously require some more TLC before they're bullet-proof.

I think you're finding an issue that I also encountered in a difference project.  You can see the dev-branch where I added an input `pad_values` that's a numeric vector of slots that should be padded.  It arises because VAST has intercepts etc that `model-matrix` treats differently when implementing a corner-constraint.  So sometimes `model.matrix` and hence `effects` gets confused about what length of vector for covariates to expect.  

You willing to explore a bit and then respond on this thread whether it fixes things or not?  And feel free to also respond if my description is not sufficient to get you going :0

**Comment by aallyn** [comment]
Thanks, Jim! I'll have a look at the development branch and circle back here with any questions/updates. 

No worries at all on the name, welcome back!

**Comment by aallyn** [comment]
Back in business, thank you! Using the `Effect.fit_model` function on the development branch, I set `pad_values = 1` and things worked as expected for the example. The full call is:

`pred = Effect.fit_model( fit_adjust2_run,
                         focal.predictors = c("BOT_DEPTH"),
                         which_formula = "X1", 
                         xlevels = 100,
                         pad_values = 1)`

Jim -- would there be interest in being able to use the actual beta1/2 fitted parameter values when making these plots? If I am tracking things, the padding is providing another value to the parameter vector and then another row/column to the covariate matrix to account for the fact that it isn't retaining the betas as it focuses on gamma (or lambda). Those values are then input as 0s. Any reason why we would want the actual coefficients for beta1 (or 2) instead? 

Closing for now, though happy to keep chatting, thanks again!

**Comment by James-Thorson-NOAA** [comment]
Yeah, I can't think of a time when the betas (which are intercepts) would be necessary ... excluding their action means that the remaining plot shows the marginal effect w.r.t. a given covariate.  However, there's plenty of room to test and explore further;  I consider the `effects` and `pbd` plots to still be in beta-testing.

Thanks again for checking and please do keep reporting back on this thread if you have other observations or suggestions!
