### ISSUE TITLE
dev branch: TMB compile fails

### ISSUE THREAD

**Issue by Jason-Conner-NOAA** [James-Thorson-NOAA/VAST#318]
Reference issue: https://github.com/coleary-noaa/model-based-indices/issues/24

Production model code for 2021 Bering Sea Pacific cod index fails to compile the TMB object using:
TMB 1.7.22
VAST(dev) 3.9.0
VAST cpp v14_0_0
FishStatsUtils(dev) 2.11.0

Executed code (will send reprex if requested):
fit <- fit_model( "settings"=settings, 
                  "Lat_i"=Data_Geostat[,'Lat'], 
                  "Lon_i"=Data_Geostat[,'Lon'], 
                  "t_i"=Data_Geostat[,'Year'], 
                  "c_i"=rep(0,nrow(Data_Geostat)), 
                  "b_i"=Data_Geostat[,'Catch_KG'], 
                  "a_i"=Data_Geostat[,'AreaSwept_km2'], 
                  "v_i"=Data_Geostat[,'Vessel'],
                  "create_strata_per_region"=TRUE,
                  "getJointPrecision"=getJointPrecision, 
                  "getReportCovariance"=getReportCovariance,
                  "X1_formula"=formula,
                  "X2_formula"=formula,
                  "X1config_cp" <- X1config_cp,
                  "X2config_cp" <- X2config_cp ,
                  "covariate_data"=covariate_data,
                  "Npool" = Npool,
                  "test_fit" = TRUE,
                  "working_dir" = workDir,
                  "CompileDir" = TMBdir
                  
                  
)

Results in error:
Error in TMB::compile(file = paste0(Version, ".cpp"), flags = "-Wno-ignored-attributes -O2 -mfpmath=sse -msse2 -mstackrealign") :
Compilation failed

This does not occur with main branch:
VAST 3.8.2
FishStatsUtils 2.10.2
VAST_v13_1_0.cpp

**Comment by James-Thorson-NOAA** [comment]
I think this is because you're using the CRAN version of TMB with the dev branch of VAST ... the VAST@dev is testing a new epsilon-correction speedup using TMB function `newton::tag` that is only available on the TMB GitHub branch.  

Until the TMB GitHub has a numeric release, I'm disabling the new feature on the VAST@dev branch to avoid this issue.  I'll close here for now, but feel free to keep the thread going and happy to re-open if the problem isn't solved!
