### ISSUE TITLE
one important comment about the MICE model in VAST

### ISSUE THREAD

**Issue by Hanqingpeng** [James-Thorson-NOAA/VAST#339]
I recently wanted to study the effects of biological interactions on fishery population dynamics using a MICE model.

But I learned this important piece of information from a helper:” Just one important comment about the MICE model in VAST: Thorson et al. (2019) is the only paper to have used the MICE model and, since then, many other people have tried to develop a MICE model in VAST but have faced problems. Jim Thorson himself has faced problems with the MICE model since Thorson et al. (2019) and has discouraged VAST users to use the MICE model in VAST for now.”

He encourage me to send the email to you to ask whether using the MICE model in VAST is still discouraged or whether you has solved the problems with the MICE model. 

 

In addition, could you give me some research suggestions for using VAST to study biological interactions and the impact of future climate change on fishery stocks?

**Comment by James-Thorson-NOAA** [comment]
Thanks for asking here where we can discuss and get others' input ... feel free to link the helper :)

So I often discourage using the MICE because:

1. it's important to understand simple models before trying complex, so I encourage simpler models first;
2. often problems can be addressed in simpler ways;
3. it's very slow to estimate compared with other settings

However, some problems need the MICE-in-space feature (technically a VAM) and then it's a good idea.

It's currently disabled on dev-branch (to simplify adding some forecasting options), but if you have a bunch of time to explore, and are interested in collaborating, I could certainly add it back in.

And to model biological interactions:

1. are implicitly included in joint models using factor-model to estimate cross-correlations;
2. are explicitly included when including spatially varying response to traits as density covariates (email me, a paper is in revision)
3. can be explored post-hoc via clustering and ordination;
4. then MICE is sort-of the most complicated "last" resort IMHO

**Comment by agruss2** [comment]
Thanks a lot, it is very useful to share and discuss this issue here :)
Jim - This is a detailed and very useful summary. 
Qingpeng - I agree with Jim and think that you should start with a joint model using the factor-model to estimate cross-correlations, i.e., develop a VAST model with multiple categories where the categories are species/taxa/life stages, and produce results/figures with this multi-category model, and we'll then go from there. 
Please let us know what you think. Please feel free to email me if you need my help to set up the multi-category VAST model.

**Comment by Hanqingpeng** [comment]
Thanks a lot! About the joint models using factor-model:
1) How does VAST exclude the effects of other factors, such as environmental changes, in order to determine that the influences on the spatio-temporal dynamics of populations are determined by biological interactions (i.e., using VAST to separate effects of environment and biological interactions)?
2) Another perception is that changes in biological interactions are driven by environmental change and fishing.    

If the former is correct, it is suggested that the authors write a paper as a guide to the use of VAST for everyone.

**Comment by James-Thorson-NOAA** [comment]
Thanks for following up.

Since this thread, tinyVAST has a much easier interface to combine cross-lagged interactions (which I've called a MICE-in-space model, after Models of Intermediate Complexity) and other structural models.  For example, see the bivariate demo [here](https://vast-lib.github.io/tinyVAST/articles/web_only/VAST.html#bivariate-spatio-temporal-autoregressive-model).  tinyVAST is in alpha-release, and I'd be happy to get feedback on the [discussion board](https://github.com/vast-lib/tinyVAST/discussions)  

If correctly specified, these could presumably separate environmental drivers and biological interactions.  However, in practices these models will always be approximations to a true data-generating process, and results from an attribution analysis should be treated with some caution.

And of course I'd be happy to hear your thoughts on how better to document these concepts and ideas, whether journal articles, reference docs, vignettes etc.  Some of it is now in our [recent textbook](https://www.taylorfrancis.com/books/mono/10.1201/9781003410294/spatio-temporal-models-ecologists-james-thorson-kasper-kristensen).  

I'm closing for now, but happy to keep discussing.
