### ISSUE TITLE
Interpreting Results and unitless a_i

### ISSUE THREAD

**Issue by abesolberg** [James-Thorson-NOAA/VAST#340]
Hi Jim, this is more of a question than an issue, so I will close it shortly, I'm running a seasonal model using the results from an ongoing inshore gillnet survey. The purpose of the model is to see if there have been changes in species arrival timing (week of peak CPUE) across time and space. Consequentially, I'm less interested in the Index/Density values of a knot, but rather how they rank against themselves within and across years. I'm using VAST for this because survey timing is not always consistent, so while there is always some crossover between areas, not every area is being sampled in the same bi-weekly period, which is what I am using for my season. Early versions of the model run, but I still need to adjust some parameters.  

I wanted to confirm that I was interpreting my results correctly. My `b_i` variable is CPUE, and my `a_i` variable is unitless 1. Because of this, I think both my Index and my Density outputs are meaningless by themselves, but I should be able to compare them relative to other model values to get a rough trendline of species timing. Am I interpreting that correctly? I also wanted to know if I could change my `a_i` variable to total nets, and my `b_i` to total catch? If I did that, would my density output be CPUE? 

Thanks in advance, and feel free to close this if this is not the appropriate forum.

**Comment by James-Thorson-NOAA** [comment]
Thanks for asking on the publicly searchable forum, I think this is a great place for the thread.

Yes, you could do:

```R
install_unit("net")
b_i = as_units( 1:10, "count")
a_i = as_units(  rep(1,10), "net")
```

and the resulting index would have units `Units: [count/net*km2]`.  You could then compare across values (which is a ratio of common units, i.e., dimensionless), or have process research defining the effective area of each net, with units `Units: [km2/net]`, such that the product of this and the index as units `Units: [count]` which makes sense.

Alternatively, you could define:

```R
install_unit("catch_per_net")
b_i = as_units( 1:10, "catch_per_net")
a_i = as_units(  rep(1,10), unitless)
```

and the resulting index would have units `Units: [catch_per_net*km2]`, where again some external or internal estimate of catchability coefficient would have units `Units: [km2/net]` such that the index is properly in units of `Units: [catch]`

I'll close for now but feel free to keep discussing if interested.

**Comment by abesolberg** [comment]
Thanks, Jim. Thank you! This is helpful. A bit more re: result interpretation, is there a reason why I'm getting these results when looking at my indices? 

`all(fit$Report$Index_gctl > 0)` # Returns True
`all(units::drop_units(fit$Report$Index_ctl) > 0)` # Returns False
`all(units::drop_units(fit$Report$D_gct) > 0)` # Returns False

My understanding was that the following code should all return true

`all(apply(fit$Report$Index_gctl , 3 , sum) == fit$Report$Index_ctl)`
`all((fit$Report$D_gct[,1,1] * fit$spatial_list$a_gl) == fit$Report$Index_gctl[,1,1,])`

or that the total index was the sum over time of the grid index, and that the grid density was equal to the grid index divided by the grid area.

If it is relevant, I am running a model where not all areas are sampled at the same time, but I am trying to get contemporaneous index estimates (similar to the wiki/paper for seasonal models). Thanks in advance!

**Comment by James-Thorson-NOAA** [comment]
yeah, thanks for asking!  

there's two things happening:
1.  For any year with no data or no encounters, when `settings$treat_nonencounter_as_zero=TRUE`, VAST sets those years to zero post-doc.  This mimics the default behavior of many implementations of design-based estimators.  I assume `units::drop_units(fit$Report$Index_ctl)` includes some 0 values due to this.
2.  Yes, using default `Expansion_cz` settings the sum of area*density is the index in REPORTed variables (epsilon bias-correction complicates this in other outputs, but doesn't affect the REPORT output).  I'm not sure if you're claiming this isn't happening in your case, but please try replicating the internal code in the CPP if you wanna check ... all of the REPORTed variables are there, and you can see [amend_output](https://rdrr.io/github/James-Thorson/FishStatsUtils/src/R/amend_output.R) for logical code of implementing fix-at-zero rules.
