### ISSUE TITLE
Two questions about multi-species VAST models

### ISSUE THREAD

**Issue by agruss2** [James-Thorson-NOAA/VAST#346]
I had some questions about multi-species VAST models, please, and thought that the answers may interest others, so I'm posting the questions here: 

**(1)** One major benefit of fitting a multi-species VAST model is to get results for data-poor species, which may not be possible with single-species VAST models for those data-poor species. 
When fitting a multi-category VAST model where the categories are age classes, length classes or prey categories, the Omega and Epsilon elements of the FieldConfig object are all set to "IID":
`$FieldConfig
        Component_1 Component_2
Omega   "IID"       "IID"      
Epsilon "IID"       "IID"`      
As far as I know, all existing multi-species VAST models have been developed to conduct ordination, except for Thorson & Barnett (2017). In Thorson & Barnett (2017), the number of factors (n_f) was set equal to the number of species considered in the VAST model (n_c).
However, I am currently developing multi-species VAST models only because I need to get results with VAST for several species, many of which are data-poor, and I am not interested in ordination but rather only in estimating common R terms (correlations among locations) for all species in the same VAST model. 
Thus, as it seems to be a little bit unconventional to fit a multi-species VAST model where the Omega and Epsilon elements of the FieldConfig object are all set to "IID", I wanted to check if this was OK or not? Or would you recommend me to proceed as in Thorson & Barnett (2017) and set all the Omega and Epsilon elements of the FieldConfig object equal to n_c (i.e., equal to the number of species considered in the VAST model)?

**(2)** Looking at the ordination example (https://github.com/James-Thorson-NOAA/VAST/wiki/Ordination), I can see that all categories have exactly the same number or records. 
However, is it correct to fit a multi-category or multi-species model where all categories do not necessarily have the same number of records? 
For example, let's imagine that we are dealing with two species, Species 1 and Species 2 and that we have 1000 (zero and non-zero) records for each of these species. However, 10 of the records for Species 1 are NA's or clear outliers and, therefore, need to be dropped. In that situation, it is OK to fit a VAST model to 990 records for Species 1 and 1000 records for Species 2. Or does one absolutely need to fit the VAST model to 990 records for Species 1 and the corresponding 990 records for Species 2 (e.g., the 990 records for Species 2 that correspond to the haul IDs for the 990 records for Species 1)? 

Many thanks!

**Comment by James-Thorson-NOAA** [comment]
1)  Yeah, I think if you wanna use the indices in some subsequent assessment model then you should use "IID" omega and epsilon to avoid unduly shrinking towards a shared trend.  This is the same rationale as for expanding [age/length comp data](https://cdnsciencepub.com/doi/abs/10.1139/cjfas-2018-0015).  and I agree that sharing kappa and H parameters can allow reasonable fits to species that are otherwise too data poor.  For very data poor species, you can also explore using argument `Npool` to share values for measurement error `SigmaM` and omega/epsilon variance parameters between data-rich and data-poor species.  Finally, an in-press paper about trait-based models suggests another avenue ... using species traits to shrink data-poor species towards the trait-weighted average of data-rich species.  I'm happy to discuss this on this issue thread if anyone's interested, and could share a link in a while (paper describing it has minor revisions @ Ecography)

2)  And yeah, no worries about having different spatial coverage (within reason) for different model components.  This is essentially what we've done already, e.g., for [stomach expansion](https://onlinelibrary.wiley.com/doi/abs/10.1111/faf.12457)

closing for now but happy to keep discussing

**Comment by agruss2** [comment]
Hi Jim, thanks a lot for your prompt and detailed reply which is very much appreciated :) It is very useful to have this feeedback, and I'm gonna follow up with you via email. 
Talk soon!
