### ISSUE TITLE
Use of the faster epsilon bias-correction estimator causing issues

### ISSUE THREAD

**Issue by agruss2** [James-Thorson-NOAA/VAST#351]
Hello, 
I am using the very latest version of VAST (i.e., Version 3.10.0) and have an issue with the new "faster epsilon bias-correction estimator" that is now available in VAST. 
If I turn bias-correction on, model estimation does not exit properly, so that I cannot get any `fit` object despite the fact that a "parameter_estimates.txt" file has been saved in my machine. 
Here is the error message that I get:
```R
### Applying faster epsilon bias-correction estimator
Error in getUserDLL() : 
  Multiple TMB models loaded. Failed to guess DLL name.
```
If I turn bias-correction off, then model estimation exits properly and I can get a `fit` object. 
Here are my questions, please:
(1) Can you identify where the problem may come from with the faster epsilon bias-correction estimator implemented in VAST Version 3.10.0?
(2) Is there any way the VAST users can turn off the "faster epsilon bias-correction estimator" and use the previous, slower version of the bias-correction?
Many thanks!

**Comment by James-Thorson-NOAA** [comment]
Sorry to hear this!  You can always use `fit_model( ..., use_new_epsilon=FALSE)` to disable the new epsilon-correction approach.  

But if I make a dev-branch to test a fix, would you be willing to test that to see if it fixes it while also allowing you to use the faster epsilon-method?

I'd appreciate the help in testing a fix, given that I can't replicate the problem on my machine and therefore can't test the fix I envision locally.

(closing for now but hoping we can keep discussing)

**Comment by agruss2** [comment]
@James-Thorson-NOAA Yes, I will be happy to help testing and fixing this issue as doing so will be useful not only for me but also for other VAST users. Therefore, please go ahead and make a dev-branch to test a fix and I will test that locally to check whether the issue is solved.
Many thanks!

**Comment by James-Thorson-NOAA** [comment]
I just added a few lines to function `apply_epsilon` in VAST.  

Could you please update using `remotes::install_github("james-thorson-NOAA/VAST@dev", dep=FALSE, force=TRUE)` and re-try whatever script sequence was causing the error, and report back here?

**Comment by agruss2** [comment]
Hi Jim, I just did what you suggested, but unfortunately model estimation is still being exited - this time the error message is: 
```R
### Applying faster epsilon bias-correction estimator
Error in MakeADFun(data = Data, parameters = New_params, map = Map, random = Random,  : 
  '_TMBad' was not found in the list of loaded DLLs. Forgot to dyn.load(dynlib('_TMBad')) ?
```
What do you think should be done?
Thank you very much!

**Comment by James-Thorson-NOAA** [comment]
what's your `packageVersion("FishStatsUtils")` and `packageVersion("VAST")` ...?

**Comment by agruss2** [comment]
VAST:
Version: 3.10.0
Date: 2022-11-18
FishStatsUtils:
Version: 2.12.0
Date: 2022-11-18

**Comment by James-Thorson-NOAA** [comment]
can you send me the script you're using, and the object created by `saveRDS( fit, "fit.Rds")` where fit is the output of `fit_model`?

I'm unfortunately a bit stumped ... as I said, I can't replicate the problem and the terminal-message for the error doesn't make sense to me :0

**Comment by aallyn** [comment]
If it helps with sleuthing this, I ran into an error that sounds related. If I try to run the Wiki index standardization example, I get 
`Error in (function (b_i, a_i, t_i, c_iz = rep(0, length(b_i)), e_i = c_iz[,  : `Version` provided does not match the list of possible values`. 
I can get around that error, maybe not surprisingly, if I set `settings$Version = "VAST_v14_0_1"` and then fit the model. I haven't tried the most recent dev branch, though this was based on dev branch just before the commit with the experiment and same package versions as Arnaud.

**Comment by agruss2** [comment]
@aallyn Many thanks for your message :) I am using the latest version of "VAST_v14_0_1". But if I use the previous, slower version of the bias-correction method with "VAST_v14_0_1", then model estimation runs without any problems. 
So, @James-Thorson-NOAA, I think that something may need to be fixed in the new bias-correction method to avoid model estimation being exited before the `fit` object is generated. I am wondering if this has anything to do with the current `reload_model` function? Anyway, I am gonna send you what you requested so that you can explore the issue further if you have time. 
Thanks a lot to you both once again.

**Comment by aallyn** [comment]
Gotcha -- went down a little rabbit hole with this last night. For what it's worth, it seems like the Version being saved in settings is "VAST_v14_0_1_TMBad." This gets passed into `make_model` and is used to create a `Version_framework` object as `Version_framework = paste0(Version, "_", framework)` where `framework = "TMBad"` is the default for the latest `make_model` function, and then finally `Version_framekwork` is used by TMB::compile, TMB::dyn.lib and MakeADFun function. I could be missing something, though if that is the case, all of these are looking for a compiled file called "VAST_v14_0_1_TMBad_TMBad.cpp" rather than "VAST_v14_0_1_TMBad.cpp"?

**Comment by agruss2** [comment]
@James-Thorson-NOAA @aallyn 
Excellent news: I just followed Jim's instructions and model estimation now works perfectly with the faster bias-correction method.
Therefore, the current issue has been resolved and I can close it.
Many thanks once again to you both and chat soon! :)

**Comment by aallyn** [comment]
Hey @James-Thorson-NOAA, thanks for the quick response! I deleted my FishStatsUtils and VAST library folders and then reinstalled both packages using `remotes::install_github("james-thorson-NOAA/FishStatsUtils@dev", dep=FALSE, force=TRUE)` and then `remotes::install_github("james-thorson-NOAA/VAST@dev", dep=FALSE, force=TRUE)`. I then checked the executable files and I've got a file "VAST_v14_0_1.cpp" as well as earlier versions. If I run the Wiki example and right before fitting the model check the VAST `settings$Version`, I see "VAST_v14_0_1.cpp" and all works fine for that first fit. However, during the fitting process, it copies a  "VAST_v14_0_1_TMBad.cpp" into the executable folder and compiles that c++ file. So, then if I re-run the Wiki example code and just the `make_settings` section, settings$Version is now "VAST_v14_0_1_TMBad." If I keep going and run the `fit_model` chunk, I also get the error as before `Error in (function (b_i, a_i, t_i, c_iz = rep(0, length(b_i)), e_i = c_iz[, : Version provided does not match the list of possible values`, which I think makes sense because "VAST_v14_0_1_TMBad" isn't among the options in `make_data` (lines 996-1023). 

Unfortunately, I have no clue why this is happening and if it is a pervasive issue or just something weird that I have done. I might just go ahead and set `settings$Version` manually to be what I want for now and can return to this if it crops up for other folks?

**Comment by aallyn** [comment]
Just coming back to close the loop on this after some back and forth comparison with Arnaud. It looks like in the `FishStatsUtils::get_latest_version` function, we get the list of executable files using `dir` (`thefile <- dir(thedir, full.names = FALSE, pattern = "\\.cpp"`) and then loop over those, eventually getting the maximum (`thefile = thefile[which(semantic_version == max(semantic_version))]`). With the new TMBad framework and VAST_v14_0_1, the file has two items: VAST_v14_0_1 and VAST_v14_0_1_TMBad. On my machine (Mac), the order of these is VAST_v14_0_1_TMBad, VAST_v14_0_1. On Arnaud's (and I'm guessing yours), it's the opposite order. So, I then get a Version of VAST_v14_0_1_TMBad instead of VAST_v14_0_1.

**Comment by James-Thorson-NOAA** [comment]
@aallyn could you try downloading the latest FishStatsUtils@dev and see if that fixes the issue?

I added a step to `get_latest_version` to add the extension, so that it prevents the suffix `_CppAD` or `_TMBad` from being included in the version returned.

**Comment by aallyn** [comment]
Working now with the `gsub` additions, thank you!

**Comment by James-Thorson-NOAA** [comment]
Thanks for flagging it!

I'll put a reminder to do a new numeric release on Monday, and will await any further issue-reports before then.
