### ISSUE TITLE
Pink salmon time structure

### ISSUE THREAD

**Issue by BioCatFish** [James-Thorson-NOAA/VAST#373]
Hi! I need guidance on how to set a model for pink salmon juveniles. The abundance follows a biennial structure (say more abundant in odd years). The problem is that I have missed data for half of my study area for some odd years. VAST extrapolate density on the whole study area but overestimate the total abundance for some even years (see the figure).

I suspect the decision lies in RhoConfig, but I struggle to understand what specific setting should be applied.

Thank you.

![image](https://github.com/James-Thorson-NOAA/VAST/assets/124326216/160ca803-4ce5-4dc2-9346-0aaa87c7eba9)

**Comment by James-Thorson-NOAA** [comment]
I don't understand ... you say you having missing data for some even years, but the figure saying data are missing in odd years 2015-2021.  Which is correct?

And what makes you think that the estimator is wrong in odd years 2015-2021?

**Comment by BioCatFish** [comment]
Hi Jim, thank you for the reply. It was a typo, I meant missing odd years. I'm not sure that the estimator is incorrect, but looking at the pattern during previous years, the density during odd years was higher, and only for the period when part of the data is absent the even-odd year difference disappears. That seems wrong. Moreover, if I consider separately only that part of the study area where all years have data, the even-odd pattern is observed during 2015-2021.

**Comment by James-Thorson-NOAA** [comment]
I'm still confused about the figure ... why are there extra red dots in odd years that have missing data?

Options
1.  You might consider adding an indicator covariate that is 0 for even years and 1 for odds years, and estimate a linear+SVC response to that time-series covariate.  That would give the model some information that you seem to have when interpreting the output.  However, the model doesn't have your knowledge that there's some alternating pattern, and also doesn't have any structure that would represent that.  
2. You might consider estimating an AR1 process for intercepts (betas) using RhoConfig as you say.  

The model also has some increase in predictive uncertainty in later odd years so I guess that's the model trying to account for the uncertainty arising from missing data.  

I'm closing as an Issue (given that it seems like a discussion of user settings rather than a software topic).   Please also consider joining the Slack channel on the github main page for another discusion option
